export type AppDestinations = { official?: string; ios?: string; android?: string };

export const directStoreLinks: Record<string, AppDestinations> = {
  "詐欺バスターLITE": { ios: "https://apps.apple.com/jp/app/id6756911225" },
  "Apple『探す』": { ios: "https://apps.apple.com/jp/app/%E6%8E%A2%E3%81%99/id1514844621?platform=ipad" },
  "Google デバイスを探す": { android: "https://play.google.com/store/apps/details?id=com.google.android.apps.adm" },
  "Peatix": { ios: "https://apps.apple.com/jp/app/id561632513", android: "https://play.google.com/store/apps/details?id=com.peatix.android.Azuki" },
  "Google フォト": { ios: "https://apps.apple.com/jp/app/id962194608", android: "https://play.google.com/store/apps/details?id=com.google.android.apps.photos" },
  "入退去メモ": { ios: "https://apps.apple.com/jp/app/%E5%85%A5%E9%80%80%E5%8E%BB%E3%83%A1%E3%83%A2/id6767765025" },
  "UCHITAS": { ios: "https://apps.apple.com/jp/app/id1453357489" },
  "Cabinote": { ios: "https://apps.apple.com/jp/app/%E6%8C%81%E3%81%A1%E7%89%A9-%E5%AE%B6%E8%B2%A1%E7%AE%A1%E7%90%86%E6%95%B4%E7%90%93%E4%BF%9D%E8%A8%BC%E6%9B%B8-cabinote/id6755080718" },
  "Misoca": { ios: "https://apps.apple.com/jp/app/id1026534800", android: "https://play.google.com/store/apps/details?id=jp.misoca.misoca" },
  "Toggl Track": { ios: "https://apps.apple.com/jp/app/id1291898086" },
  "GOOSE": { ios: "https://apps.apple.com/jp/app/id1565305966", android: "https://play.google.com/store/apps/details?id=jp.co.tsunamamo.kalert" },
  "つなぐノート": { ios: "https://apps.apple.com/jp/app/id6451205576" },
  "マネーフォワード ME": { ios: "https://apps.apple.com/jp/app/id594145971", android: "https://play.google.com/store/apps/details?id=com.moneyforward.android.app" },
  "保険簿": { ios: "https://apps.apple.com/jp/app/id1447375500", android: "https://play.google.com/store/apps/details?id=com.ib.hokenbo" },
  "母子モ": { ios: "https://apps.apple.com/jp/app/id1106750564", android: "https://play.google.com/store/apps/details?id=jp.co.mti.BoshiAuthorize" },
  "TimeTree": { ios: "https://apps.apple.com/jp/app/id952578473", android: "https://play.google.com/store/apps/details?id=works.jubilee.timetree" },
  "Google One バックアップ": { ios: "https://apps.apple.com/jp/app/id1451784328", android: "https://play.google.com/store/apps/details?id=com.google.android.apps.subscriptions.red" },
  "Yahoo!乗換案内": { ios: "https://apps.apple.com/jp/app/id291676451", android: "https://play.google.com/store/apps/details?id=jp.co.yahoo.android.apps.transit" },
  "GO": { ios: "https://apps.apple.com/jp/app/id1254341709", android: "https://play.google.com/store/apps/details?id=com.dena.automotive.taxibell" },
  "akippa": { ios: "https://apps.apple.com/jp/app/id894446397" },
  "ecbo cloak": { ios: "https://apps.apple.com/jp/app/id1443707795", android: "https://play.google.com/store/apps/details?id=io.ecbo.cloak" },
  "クラシル": { ios: "https://apps.apple.com/jp/app/id1059134258", android: "https://play.google.com/store/apps/details?id=com.kurashiru" },
  "くふう トクバイ": { ios: "https://apps.apple.com/jp/app/id1124772645", android: "https://play.google.com/store/apps/details?id=jp.co.tokubai.android.bargain" },
  "TABETE": { ios: "https://apps.apple.com/jp/app/id1392919676", android: "https://play.google.com/store/apps/details?id=me.tabete.tabete" },
  "Yieto 2": { ios: "https://apps.apple.com/jp/app/id6745941580" },
  "ぺとログ": { ios: "https://apps.apple.com/jp/app/id6756508276", android: "https://play.google.com/store/apps/details?id=jp.nooon.petlog" },
  "PetBacker": { ios: "https://apps.apple.com/jp/app/id1168037472", android: "https://play.google.com/store/apps/details?id=com.petbacker.android" },
  "Yahoo!防災速報": { ios: "https://apps.apple.com/jp/app/id481914139", android: "https://play.google.com/store/apps/details?id=jp.co.yahoo.android.emg" },
  "特務機関NERV防災": { ios: "https://apps.apple.com/jp/app/id1472338480", android: "https://play.google.com/store/apps/details?id=app.nerv" },
  "Yahoo!天気": { ios: "https://apps.apple.com/jp/app/id521974902" },
  "tenki.jp": { ios: "https://apps.apple.com/jp/app/id433865746", android: "https://play.google.com/store/apps/details?id=jwa.or.jp.tenkijp3" },
  "トリセツ": { ios: "https://apps.apple.com/jp/app/id1085923883", android: "https://play.google.com/store/apps/details?id=com.trygle.instructionmanualapp" },
  "お薬手帳プラス": { ios: "https://apps.apple.com/jp/app/id947740067", android: "https://play.google.com/store/apps/details?id=jp.co.nicho.jpokusuri" },
  "頭痛ーる": { ios: "https://apps.apple.com/jp/app/id602991338", android: "https://play.google.com/store/apps/details?id=jp.co.pocke.android.zutsu" },
  "CLINICS": { ios: "https://apps.apple.com/jp/app/id1106261604", android: "https://play.google.com/store/apps/details?id=life.medley.clinics" },
  "Zaim": { ios: "https://apps.apple.com/jp/app/id445850671", android: "https://play.google.com/store/apps/details?id=net.zaim.android" },
  "Moneytree": { ios: "https://apps.apple.com/jp/app/id586847189", android: "https://play.google.com/store/apps/details?id=jp.moneytree.moneytree" },
  "OsidOri": { ios: "https://apps.apple.com/jp/app/id1473751623" },
  "ぴよログ": { ios: "https://apps.apple.com/jp/app/id1252857347", android: "https://play.google.com/store/apps/details?id=jp.co.sakabou.piyolog" },
  "家族アルバム みてね": { ios: "https://apps.apple.com/jp/app/id935672069", android: "https://play.google.com/store/apps/details?id=us.mitene" },
  "Google Authenticator": { ios: "https://apps.apple.com/jp/app/id388497605", android: "https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2" },
  "Microsoft Authenticator": { ios: "https://apps.apple.com/jp/app/id983156458", android: "https://play.google.com/store/apps/details?id=com.azure.authenticator" },
  "Twilio Authy": { ios: "https://apps.apple.com/jp/app/id494168017", android: "https://play.google.com/store/apps/details?id=com.authy.authy" },
  "Whoscall": { ios: "https://apps.apple.com/jp/app/id929968679", android: "https://play.google.com/store/apps/details?id=gogolook.callgogolook2" },
  "ジョルダン乗換案内": { ios: "https://apps.apple.com/jp/app/id299490481", android: "https://play.google.com/store/apps/details?id=jp.co.jorudan.nrkj" },
  "乗換NAVITIME": { ios: "https://apps.apple.com/jp/app/id528532387" },
  "クックパッド": { ios: "https://apps.apple.com/jp/app/id340368403", android: "https://play.google.com/store/apps/details?id=com.cookpad.android.activities" },
  "DELISH KITCHEN": { ios: "https://apps.apple.com/jp/app/id1177907423", android: "https://play.google.com/store/apps/details?id=tv.every.delishkitchen" },
  "Shufoo!": { ios: "https://apps.apple.com/jp/app/id373909230", android: "https://play.google.com/store/apps/details?id=com.toppan.shufoo.android" },
  "さんあ〜る": { ios: "https://apps.apple.com/jp/app/id977071564", android: "https://play.google.com/store/apps/details?id=jp.co.delight_system.threeR.android" },
  "EPARKお薬手帳": { ios: "https://apps.apple.com/jp/app/id952969231", android: "https://play.google.com/store/apps/details?id=jp.epark.medicinenote" },
  "Google Keep": { ios: "https://apps.apple.com/jp/app/id1029207872", android: "https://play.google.com/store/apps/details?id=com.google.android.keep" },
};
